const router = require("express-promise-router")();
const { userRoute, userRouter } = require('./user/route');
const { coachRoute, coachRouter } = require('./coach/route');
const {courseRoute,courseRouter}=require('./course/route');
const {blogpostRoute,blogpostRouter}=require('./blogpost/route');
const{dashboardRoute,dashboardRouter} = require('./dashboard/route');
const{toDoListRoute,toDoListRouter} = require('./todolist/route');
router.use(userRoute.BaseRoute, userRouter);
router.use(coachRoute.BaseRoute, coachRouter);
router.use(courseRoute.BaseRoute,courseRouter);
router.use(blogpostRoute.BaseRoute,blogpostRouter);
router.use(dashboardRoute.BaseRoute,dashboardRouter);
router.use(toDoListRoute.BaseRoute,toDoListRouter);
module.exports = { appRouter: router };